server:
  port: 8081
logging:
  level:
    com.alibaba.otter.canal.client.adapter.hbase: DEBUG
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null


hbasezookeeper.quorum: 127.0.0.1
hbase.zookeeper.property.clientPort: 2181
hbase.zookeeper.znode.parent: /hbase

canal.conf:
  canalServerHost: 127.0.0.1:11111
#  zookeeperHosts: slave1:2181
#  bootstrapServers: slave1:6667 #or rocketmq nameservers:host1:9876;host2:9876
  flatMessage: true
  canalInstances:
  - instance: example
    groups:
    - outAdapters:
      - name: logger
#      - name: hbase
#        properties:
#          hbase.zookeeper.quorum: ${hbase.zookeeper.quorum}
#          hbase.zookeeper.property.clientPort: ${hbase.zookeeper.property.clientPort}
#          zookeeper.znode.parent: ${hbase.zookeeper.znode.parent}
#  mqTopics:
#  - mqMode: kafka
#    topic: example
#    groups:
#    - groupId: g2
#      outAdapters:
#      - name: logger
#  mqTopics:
#  - mqMode: rocketmq
#    topic: example
#    groups:
#    - groupId: g2
#      outAdapters:
#      - name: logger

#adapter.conf:
#  datasourceConfigs:
#    defaultDS:
#      url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true
#      username: root
#      password: 121212
#  adapterConfigs:
#  - hbase/mytest_person2.yml
